<a href="https://colab.research.google.com/github/WiktoriaSulkiewicz/data-science-bootcamp/blob/main/Data_Science_Bootcamp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print('Hello colab')

Hello colab


In [2]:
'hello colab'

'hello colab'

In [3]:
import numpy as np


In [4]:
np.__version__


'1.21.6'

In [ ]:
print(dir(np))

In [6]:
x = np.array([1, 3])
x

array([1, 3])

In [7]:
print(x)

[1 3]


In [8]:
type(x)

numpy.ndarray

wymiar tabeli

In [9]:
x.ndim

1

kształt tabeli

In [10]:
x.shape

(2,)

liczba elementów w tablicy

In [11]:
x.size

2

In [12]:
x.dtype

dtype('int64')

In [13]:
y=np.array([1.2,1.3,4.5,5.6])
print(y)

[1.2 1.3 4.5 5.6]


In [14]:
y.dtype

dtype('float64')

**2D array **

In [15]:
x = np.array([[1, -3],[3,-6]])

In [16]:
print(x)

[[ 1 -3]
 [ 3 -6]]


In [17]:
x.ndim

2

In [18]:
x.shape

(2, 2)

In [19]:
x.size

4

In [20]:
x.dtype

dtype('int64')

In [29]:
x =np.array([[[2, 4, 5],
              [4, 5, 6]],
              
             [[2, 4, 5,],
              [3, 4, 5,]]])
print(x)

[[[2 4 5]
  [4 5 6]]

 [[2 4 5]
  [3 4 5]]]


In [25]:
x.shape

(2, 2, 3)