<a href="https://colab.research.google.com/github/WiktoriaSulkiewicz/data-science-bootcamp/blob/main/Data_Science_Bootcamp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
print('Hello colab')

Hello colab


In [3]:
'hello colab'

'hello colab'

In [4]:
import numpy as np


In [5]:
np.__version__


'1.21.6'

In [ ]:
print(dir(np))

In [7]:
x = np.array([1, 3])
x

array([1, 3])

In [8]:
print(x)

[1 3]


In [9]:
type(x)

numpy.ndarray

wymiar tabeli

In [10]:
x.ndim

1

kształt tabeli

In [11]:
x.shape

(2,)

liczba elementów w tablicy

In [12]:
x.size

2

In [13]:
x.dtype

dtype('int64')

In [14]:
y=np.array([1.2,1.3,4.5,5.6])
print(y)

[1.2 1.3 4.5 5.6]


In [15]:
y.dtype

dtype('float64')

**2D array **

In [16]:
x = np.array([[1, -3],[3,-6]])

In [17]:
print(x)

[[ 1 -3]
 [ 3 -6]]


In [18]:
x.ndim

2

In [19]:
x.shape

(2, 2)

In [20]:
x.size

4

In [21]:
x.dtype

dtype('int64')

In [22]:
x =np.array([[[2, 4, 5],
              [4, 5, 6]],
              
             [[2, 4, 5,],
              [3, 4, 5,]]])
print(x)

[[[2 4 5]
  [4 5 6]]

 [[2 4 5]
  [3 4 5]]]


In [23]:
x.shape

(2, 2, 3)

In [24]:
A = np.array([2, 4, 5], dtype = 'complex')

In [25]:
print(A)

[2.+0.j 4.+0.j 5.+0.j]


In [27]:
np.zeros(shape = (2, 4, 3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [28]:
np.ones(shape=(2,3,3), dtype='int')

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [29]:
np.full(shape = (2,3,3), fill_value = 6, dtype = 'int')

array([[[6, 6, 6],
        [6, 6, 6],
        [6, 6, 6]],

       [[6, 6, 6],
        [6, 6, 6],
        [6, 6, 6]]])

In [30]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [32]:
range(10)
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [33]:
np.arange(start=3, stop=5)

array([3, 4])

In [34]:
np.arange(start = 0, stop = 12, step= 2)

array([ 0,  2,  4,  6,  8, 10])

In [36]:
np.linspace(start = 0, stop = 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [41]:
A = np.arange(12)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [45]:
A.reshape(3,4)


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [46]:
A.reshape(4, -1)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [52]:
A = np.array([1, 3, 4, 5])
B = np.array([2, 4, 5,8])

In [53]:
A-B

array([-1, -1, -1, -3])

In [54]:
A+B

array([ 3,  7,  9, 13])

In [56]:
A*B

array([ 2, 12, 20, 40])

In [57]:
A + 3 

array([4, 6, 7, 8])

In [58]:
np.add(A, B)

array([ 3,  7,  9, 13])

In [60]:
np.subtract(A, B)

array([-1, -1, -1, -3])

In [61]:
np.multiply(A, B)

array([ 2, 12, 20, 40])

In [62]:
np.divide(A, B)

array([0.5  , 0.75 , 0.8  , 0.625])

In [65]:
X = np.array([[2, 4], [3,5]])
Y = np.array([[6, -1], [3, -2]])
print(X, '\n')
print(Y)

[[2 4]
 [3 5]] 

[[ 6 -1]
 [ 3 -2]]


Mnożenie macierzy

In [66]:
np.dot(X, Y)

array([[ 24, -10],
       [ 33, -13]])

In [67]:
X.dot(Y)

array([[ 24, -10],
       [ 33, -13]])

In [68]:
Y.dot(X)

array([[ 9, 19],
       [ 0,  2]])

In [69]:
X @ Y

array([[ 24, -10],
       [ 33, -13]])

In [75]:
np.random.seed(0)

In [81]:
np.random.randint(6)

5

In [77]:
np.random.randn(2,4)

array([[ 1.12279492,  0.30280522,  0.07085926,  0.07304142],
       [-1.42232584,  1.52006949, -0.29139398, -0.13309028]])

In [78]:
np.random.rand(2)

array([0.27265629, 0.47766512])

In [83]:
np.random.randint(low=10, high=101, size=2)

array([87, 82])

In [84]:
np.random.choice([2,3,4,5])

3

In [87]:
np.random.choice(['raz', 'dwa', 'sześć'])

'dwa'

In [89]:
data = np.arange(5)
data

array([0, 1, 2, 3, 4])

In [90]:
np.random.shuffle(data)
data

array([3, 1, 4, 2, 0])

In [91]:
np.exp(1)

2.718281828459045

In [92]:
np.sqrt(9)

3.0

In [96]:
np.all([1, 0, 4])

False

In [97]:
np.any([0, 0, 0])

False

In [98]:
bool(0)

False

In [99]:
bool(-1)

True

In [101]:
A = np.random.rand(4)
A

array([0.14335329, 0.94466892, 0.52184832, 0.41466194])

In [103]:
A[np.argmax(A)]

0.9446689170495839

In [104]:
np.argmin(A)

0

In [105]:
np.argsort(A)

array([0, 3, 2, 1])

In [106]:
np.argmax(A)

1

In [107]:
np.max(A)

0.9446689170495839

In [108]:
np.mean(A)

0.5061331165498064

In [109]:
np.median(A)

0.46825513087029763

In [110]:
np.std(A)

0.28833001776046735

**Indeksowanie wycinanie tablic**

In [111]:
A =np.arange(10)
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [113]:
A[2:]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [114]:
A[2]

2

In [115]:
A[:2]

array([0, 1])

In [116]:
A[[3,5]]

array([3, 5])

In [117]:
A[-1]

9

In [118]:
A[2:4]

array([2, 3])

In [119]:
A = A.reshape(2,5)
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [120]:
A[0]

array([0, 1, 2, 3, 4])

In [121]:
A[:,3]

array([3, 8])

In [128]:
A[1,0:3]

array([5, 6, 7])

In [129]:
A[0,1]=21
A

array([[ 0, 21,  2,  3,  4],
       [ 5,  6,  7,  8,  9]])

Iteracja po tablicach

In [130]:
A

array([[ 0, 21,  2,  3,  4],
       [ 5,  6,  7,  8,  9]])

In [131]:
for row in A:
  print(row)


[ 0 21  2  3  4]
[5 6 7 8 9]


In [132]:
for i in A:
  print(i)

[ 0 21  2  3  4]
[5 6 7 8 9]


In [137]:
for row in A:
  print(row[:3])

[ 0 21  2]
[5 6 7]


In [138]:
for item in A.flat:
  print(item)

0
21
2
3
4
5
6
7
8
9


Zmiana rozmiaru tablic

In [139]:
A

array([[ 0, 21,  2,  3,  4],
       [ 5,  6,  7,  8,  9]])

In [140]:
A.reshape(5,2)

array([[ 0, 21],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9]])

In [142]:
A.ravel()

array([ 0, 21,  2,  3,  4,  5,  6,  7,  8,  9])

In [143]:
A.T

array([[ 0,  5],
       [21,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9]])

Maski logiczne

In [150]:
A =np.arange(start=-20, stop=20, step=0.5)
A

array([-20. , -19.5, -19. , -18.5, -18. , -17.5, -17. , -16.5, -16. ,
       -15.5, -15. , -14.5, -14. , -13.5, -13. , -12.5, -12. , -11.5,
       -11. , -10.5, -10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,
        -6.5,  -6. ,  -5.5,  -5. ,  -4.5,  -4. ,  -3.5,  -3. ,  -2.5,
        -2. ,  -1.5,  -1. ,  -0.5,   0. ,   0.5,   1. ,   1.5,   2. ,
         2.5,   3. ,   3.5,   4. ,   4.5,   5. ,   5.5,   6. ,   6.5,
         7. ,   7.5,   8. ,   8.5,   9. ,   9.5,  10. ,  10.5,  11. ,
        11.5,  12. ,  12.5,  13. ,  13.5,  14. ,  14.5,  15. ,  15.5,
        16. ,  16.5,  17. ,  17.5,  18. ,  18.5,  19. ,  19.5])

In [151]:
A.reshape(-1,10)

array([[-20. , -19.5, -19. , -18.5, -18. , -17.5, -17. , -16.5, -16. ,
        -15.5],
       [-15. , -14.5, -14. , -13.5, -13. , -12.5, -12. , -11.5, -11. ,
        -10.5],
       [-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,  -6.5,  -6. ,
         -5.5],
       [ -5. ,  -4.5,  -4. ,  -3.5,  -3. ,  -2.5,  -2. ,  -1.5,  -1. ,
         -0.5],
       [  0. ,   0.5,   1. ,   1.5,   2. ,   2.5,   3. ,   3.5,   4. ,
          4.5],
       [  5. ,   5.5,   6. ,   6.5,   7. ,   7.5,   8. ,   8.5,   9. ,
          9.5],
       [ 10. ,  10.5,  11. ,  11.5,  12. ,  12.5,  13. ,  13.5,  14. ,
         14.5],
       [ 15. ,  15.5,  16. ,  16.5,  17. ,  17.5,  18. ,  18.5,  19. ,
         19.5]])

In [152]:
A>0

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True])

In [153]:
A[A>0]

array([ 0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,
        6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5, 11. ,
       11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5, 16. , 16.5,
       17. , 17.5, 18. , 18.5, 19. , 19.5])

In [156]:
A[np.argmax(A)]

19.5

In [159]:
np.bitwise_and(A>5, A<6)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False,  True, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False])

In [160]:
A[np.bitwise_and(A>5, A<6)]

array([5.5])