<a href="https://colab.research.google.com/github/WiktoriaSulkiewicz/data-science-bootcamp/blob/main/Data_Science_Bootcamp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print('Hello colab')

Hello colab


In [2]:
'hello colab'

'hello colab'

In [4]:
import numpy as np


In [5]:
np.__version__


'1.21.6'

In [ ]:
print(dir(np))

In [7]:
x = np.array([1, 3])
x

array([1, 3])

In [8]:
print(x)

[1 3]


In [9]:
type(x)

numpy.ndarray

wymiar tabeli

In [10]:
x.ndim

1

kształt tabeli

In [11]:
x.shape

(2,)

liczba elementów w tablicy

In [12]:
x.size

2

In [13]:
x.dtype

dtype('int64')

In [15]:
y=np.array([1.2,1.3,4.5,5.6])
print(y)

[1.2 1.3 4.5 5.6]


In [16]:
y.dtype

dtype('float64')

**2D array **

In [18]:
x = np.array([[1, -3],[3,-6]])

In [19]:
print(x)

[[ 1 -3]
 [ 3 -6]]


In [20]:
x.ndim

2

In [22]:
x.shape

(2, 2)

In [23]:
x.size

4

In [24]:
x.dtype

dtype('int64')